### ISSUE TITLE
feature request: Permalink

### ISSUE THREAD

**Issue by Dirk--** [ttnmapper/ttnmapper-web#11]
please add permalink (lon / lat / zoom / layer):
Would love to have the ability to share a view!

**Comment by jpmeijers** [comment]
I believe what you are looking for is already available:
https://github.com/ttnmapper/ttnmapper-web/blob/master/web/common.js#L17
and for layer
https://github.com/ttnmapper/ttnmapper-web/blob/master/web/common.js#L100

**Comment by Dirk--** [comment]
yes, e.g.
 https://ttnmapper.org/?lat=51.57252&lon=6.76092&zoom=16
works, but
having a button or an obvious url-rewrite would ease sharing for the less experienced a lot ....

**Comment by jpmeijers** [comment]
Yes, I get your point, but for now I don't want to make it too obvious, as it might change in the near future. The React based frontend we've been working on has urls that change as one scroll and zoom.
