### ISSUE TITLE
ttnmapper not plotting data

### ISSUE THREAD

**Issue by icepicknz** [ttnmapper/ttnmapper-web#14]
Hi,

I just logged this to tile-map-server but realised it might be better here..

The last 2 days it appears TTNMapper has been broken, nothing showing up on the heat map and I cant bring up anything in advanced maps for specific devices either. Its like the DB server has been disconnected and not able to pull the data and plot? Tried on multiple browsers and devices.

**Comment by jpmeijers** [comment]
I see there is an issue with the heatmap. Database could be affected too. I'm keeping an eye on both.

**Comment by icepicknz** [comment]
seems resolved now so you must have fixed it :) thanking you

**Comment by tomtobback** [comment]
hi, i may have a related problem, my measurements logged with the android app on 17/12/2021 show up in advanced maps (gw-id: cassiopeia-lps8, and also using my dev-id), but not on the main map yet. my gateway shows up.
