### ISSUE TITLE
Advanced map -> gateway data: map keeps loading forever. Fetching data, please be patient.

### ISSUE THREAD

**Issue by mvdswaluw** [ttnmapper/ttnmapper-web#4]
http://ttnmapper.org/gateways/?gateway=eui-b827ebfffef37f7f&startdate=2019-12-30&enddate=2019-12-30&gateways=on&lines=on&points=on

**Comment by jpmeijers** [comment]
Fixed by commit 37bd1e4a9df57df4e9f3e5cb583c6d229e523ca7

**Comment by enwi** [comment]
Same for me with devices and gateway data:
http://ttnmapper.org/devices/?device=heltec&startdate=&enddate=&gateways=on&lines=on&points=on
http://ttnmapper.org/gateways/?gateway=eui-58a0cbfffe800c49&startdate=&enddate=&gateways=on&lines=on&points=on
Also the leaderboard shows the error: 

Notice: Undefined variable: conn in /opt/ttnmapper-oss-stack/web/leaderboard/index.php on line 211
