### ISSUE TITLE
TTN Mapper map blank

### ISSUE THREAD

**Issue by enwi** [ttnmapper/ttnmapper-web#5]
The TTN Mapper map is completely blank aka not showing any data.
The advanced maps are not working:
[device data](http://ttnmapper.org/devices/?device=heltec&startdate=&enddate=&gateways=on&lines=on&points=on)
[gateway data](http://ttnmapper.org/gateways/?gateway=eui-58a0cbfffe800c49&startdate=&enddate=&gateways=on&lines=on&points=on)

Also the leaderboard shows the error: 
`Notice: Undefined variable: conn in /opt/ttnmapper-oss-stack/web/leaderboard/index.php on line 211`

Browser console shows:
```
TypeError: gatewaysInView is undefined common.js:193:11
success http://ttnmapper.org/common.js:193
```

data of callback in that function is
```
Object { 
    error: true,
    error_message: "SQLSTATE[HY000] [2002] No such file or directory"
}
```

**Comment by jpmeijers** [comment]
The VPS on which the system is running had an issue where it was unable to access its network attached storage. A restart of the VPS solved the issue.

Unfortunately this is a side-effect of the cheap hosting that is being used. It is therefore a won't-fix/can't-fix.

**Comment by enwi** [comment]
So does this also affect data that was mapped during that time?

**Comment by jpmeijers** [comment]
I believe so yes. There is a message queue between TTN and TTN Mapper that should absorb data when there is an outage, but there is a bug that prevents data from being persisted. 

On this line:
https://github.com/ttnmapper/mysql-insert-raw/blob/932c5496528e5dc3483467cb343da346567d1c20/main.go#L145
Auto-ack should be made false, and manual acking should be done when a successful insert was done on the database.

**Comment by enwi** [comment]
Great, then I need to go do that again. Is this going to be fixed then?
